//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetCourseLesson
    {
        public string Lesson_Id { get; set; }
        public string Lesson_Name { get; set; }
        public System.TimeSpan Lesson_Duration { get; set; }
        public string Lesson_Typescript { get; set; }
        public System.DateTime Lesson_DateTime { get; set; }
        public Nullable<System.DateTime> Lesson_SessionTime { get; set; }
        public bool Lesson_Active { get; set; }
        public string Lesson_Instructor { get; set; }
        public string Lesson_Publisher { get; set; }
        public string Lesson_Photo { get; set; }
        public string Crs_Id { get; set; }
    
        public virtual AspNetCours AspNetCours { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
