//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEmployee
    {
        public string Employee_Id { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Phone { get; set; }
        public decimal Employee_Salary { get; set; }
        public bool Employee_Active { get; set; }
        public string Employee_Publisher { get; set; }
        public System.DateTime Employee_DateTime { get; set; }
        public string Employee_Photo { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
