//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetInstructor
    {
        public string Inst_Id { get; set; }
        public string Inst_Fname { get; set; }
        public string Inst_Lname { get; set; }
        public System.DateTime Inst_Bdate { get; set; }
        public string Inst_Street { get; set; }
        public string Inst_City { get; set; }
        public string Inst_Country { get; set; }
        public string Inst_Gender { get; set; }
        public string Inst_Photo { get; set; }
        public string Inst_Bio { get; set; }
        public System.DateTime Inst_DateTime { get; set; }
        public string InstCat_Id { get; set; }
        public string Usr_Id { get; set; }
    
        public virtual AspNetInstructorsCat AspNetInstructorsCat { get; set; }
    }
}
