//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetProgrameCourseGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetProgrameCourseGroup()
        {
            this.AspNetProgrameCourseGroupsInstructors = new HashSet<AspNetProgrameCourseGroupsInstructor>();
            this.AspNetProgrameCourseGroupsTimes = new HashSet<AspNetProgrameCourseGroupsTime>();
        }
    
        public string Group_Id { get; set; }
        public string Group_Name { get; set; }
        public string Crs_Id { get; set; }
        public bool Group_Active { get; set; }
    
        public virtual AspNetProgrameCours AspNetProgrameCours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetProgrameCourseGroupsInstructor> AspNetProgrameCourseGroupsInstructors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetProgrameCourseGroupsTime> AspNetProgrameCourseGroupsTimes { get; set; }
    }
}
