//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetProgrameCoursesInstructor
    {
        public string ProgrameCoursesInst_Id { get; set; }
        public string ProgrameCoursesInst_Name { get; set; }
        public string ProgrameCoursesInst_Cat { get; set; }
        public System.DateTime ProgrameCoursesInst_DateTime { get; set; }
        public string ProgrameCourses_Id { get; set; }
    }
}
