//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetJob
    {
        public string Job_Id { get; set; }
        public string Job_Title { get; set; }
        public string Job_Description { get; set; }
        public System.DateTime Job_DateTime { get; set; }
        public string Job_Photo { get; set; }
        public string Job_City { get; set; }
        public string Job_Country { get; set; }
        public string Cat_Id { get; set; }
        public bool Job_Active { get; set; }
        public string Job_Publisher { get; set; }
    
        public virtual AspNetJobsCategory AspNetJobsCategory { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
