//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetJobsCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetJobsCategory()
        {
            this.AspNetJobs = new HashSet<AspNetJob>();
        }
    
        public string Cat_Id { get; set; }
        public string Cat_Name { get; set; }
        public System.DateTime Cat_DateTime { get; set; }
        public bool Cat_Active { get; set; }
        public string Cat_Publisher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetJob> AspNetJobs { get; set; }
    }
}
