//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetCourseGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetCourseGroup()
        {
            this.AspNetCourseGroupsInstructors = new HashSet<AspNetCourseGroupsInstructor>();
            this.AspNetCourseGroupsTimes = new HashSet<AspNetCourseGroupsTime>();
        }
    
        public string Group_Id { get; set; }
        public string Group_Name { get; set; }
        public string Crs_Id { get; set; }
        public bool Group_Active { get; set; }
    
        public virtual AspNetCours AspNetCours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetCourseGroupsInstructor> AspNetCourseGroupsInstructors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetCourseGroupsTime> AspNetCourseGroupsTimes { get; set; }
    }
}
