//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetManager
    {
        public string Manager_Id { get; set; }
        public string Manager_Fname { get; set; }
        public string Manager_Lname { get; set; }
        public System.DateTime Manager_Bdate { get; set; }
        public string Manager_Street { get; set; }
        public string Manager_City { get; set; }
        public string Manager_Country { get; set; }
        public string Manager_Gender { get; set; }
        public string Manager_Photo { get; set; }
        public System.DateTime Manager_DateTime { get; set; }
        public string Usr_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
