//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetEvent()
        {
            this.AspNetEventsAcceptions = new HashSet<AspNetEventsAcception>();
        }
    
        public string Event_Id { get; set; }
        public string Event_Title { get; set; }
        public string Event_Photo { get; set; }
        public string Cat_Id { get; set; }
        public System.DateTime Event_DateTime { get; set; }
        public bool Event_Active { get; set; }
        public string Event_Publisher { get; set; }
    
        public virtual AspNetEventsCat AspNetEventsCat { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetEventsAcception> AspNetEventsAcceptions { get; set; }
    }
}
