//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetPrograme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetPrograme()
        {
            this.AspNetProgrameCourses = new HashSet<AspNetProgrameCours>();
        }
    
        public string Programe_Id { get; set; }
        public string Programe_Name { get; set; }
        public string Programe_Description { get; set; }
        public int Programe_NumCourses { get; set; }
        public decimal Programe_Price { get; set; }
        public System.DateTime Programe_StartDateTime { get; set; }
        public System.DateTime Programe_DateTime { get; set; }
        public string Programe_Photo { get; set; }
        public string Cat_Id { get; set; }
        public string Programe_Publisher { get; set; }
        public bool Programe_Active { get; set; }
        public string Programe_Duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetProgrameCours> AspNetProgrameCourses { get; set; }
        public virtual AspNetPrograme AspNetProgrames1 { get; set; }
        public virtual AspNetPrograme AspNetPrograme1 { get; set; }
        public virtual AspNetProgrammesCategory AspNetProgrammesCategory { get; set; }
    }
}
