//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudent
    {
        public string Stu_Id { get; set; }
        public string Stu_Fname { get; set; }
        public string Stu_Lname { get; set; }
        public System.DateTime Stu_Bdate { get; set; }
        public string Stu_Street { get; set; }
        public string Stu_City { get; set; }
        public string Stu_Country { get; set; }
        public string Stu_Gender { get; set; }
        public string Stu_Photo { get; set; }
        public System.DateTime Stu_DateTime { get; set; }
        public string Usr_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
