//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetNew
    {
        public string News_Id { get; set; }
        public string News_Title { get; set; }
        public string News_Description { get; set; }
        public string News_Content { get; set; }
        public System.DateTime News_DateTime { get; set; }
        public string News_Photo { get; set; }
        public bool News_Active { get; set; }
        public string News_Publisher { get; set; }
        public string Cat_Id { get; set; }
    
        public virtual AspNetNew AspNetNews1 { get; set; }
        public virtual AspNetNew AspNetNew1 { get; set; }
        public virtual AspNetNewsCategory AspNetNewsCategory { get; set; }
    }
}
