//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARKAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetProgrameCours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetProgrameCours()
        {
            this.AspNetProgrameCourseGroups = new HashSet<AspNetProgrameCourseGroup>();
        }
    
        public string Crs_Id { get; set; }
        public string Crs_Name { get; set; }
        public int Crs_Numlessons { get; set; }
        public string Crs_Level { get; set; }
        public string Crs_Description { get; set; }
        public string Crs_Photo { get; set; }
        public Nullable<int> Crs_Duration { get; set; }
        public bool Crs_Active { get; set; }
        public System.DateTime Crs_DateTime { get; set; }
        public string CrsCats_Id { get; set; }
        public decimal Crs_Price { get; set; }
        public string Crs_Publisher { get; set; }
        public string Crs_Video { get; set; }
        public string Programe_Id { get; set; }
    
        public virtual AspNetCoursesCategory AspNetCoursesCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetProgrameCourseGroup> AspNetProgrameCourseGroups { get; set; }
        public virtual AspNetPrograme AspNetPrograme { get; set; }
    }
}
